//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject
{


    public partial class AgentBooking
    {

        /// <summary>
        /// lblAgentId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAgentId;

        /// <summary>
        /// txtAgentId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAgentId;

        /// <summary>
        /// lblHotel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHotel;

        /// <summary>
        /// ddlHotels control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlHotels;

        /// <summary>
        /// lblRoomCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRoomCount;

        /// <summary>
        /// txtRoomCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRoomCount;

        /// <summary>
        /// lblCheckIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCheckIn;

        /// <summary>
        /// txtCheckIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCheckIn;

        /// <summary>
        /// lblCheckOut control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCheckOut;

        /// <summary>
        /// txtCheckOut control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCheckOut;

        /// <summary>
        /// lblDiscount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDiscount;

        /// <summary>
        /// lblDiscountValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDiscountValue;

        /// <summary>
        /// btnBookRooms control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBookRooms;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// lblStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;

        /// <summary>
        /// gvBookings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBookings;
    }
}
