//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject
{


    public partial class AgentBookingPage
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// AgentBooking1 control.
        /// </summary>
        protected global::HotelProject.AgentBooking AgentBooking1;

        /// <summary>
        /// lnkHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkHome;

        /// <summary>
        /// lnkStaffLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkStaffLogin;
    }
}
