//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject
{


    public partial class MemberBrowsing
    {

        /// <summary>
        /// lblSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSearch;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// lblFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFilter;

        /// <summary>
        /// ddlPriceRange control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPriceRange;

        /// <summary>
        /// lblSortBy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSortBy;

        /// <summary>
        /// ddlSortBy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSortBy;

        /// <summary>
        /// gvHotels control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvHotels;

        /// <summary>
        /// divDetails control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDetails;

        /// <summary>
        /// lblHotelDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHotelDetails;

        /// <summary>
        /// lblStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;
    }
}
