//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject
{


    public partial class MemberBrowsingPage
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// MemberBrowsing1 control.
        /// </summary>
        protected global::HotelProject.MemberBrowsing MemberBrowsing1;

        /// <summary>
        /// lnkHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkHome;

        /// <summary>
        /// lnkMemberLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkMemberLogin;

        /// <summary>
        /// lnkMemberRating control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkMemberRating;
    }
}
