//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.RatingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatedHotel", Namespace="http://schemas.datacontract.org/2004/07/WcfHotelService")]
    [System.SerializableAttribute()]
    public partial class RatedHotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelProject.RatingServiceReference.Address HotelAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelProject.RatingServiceReference.Address HotelAddress {
            get {
                return this.HotelAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAddressField, value) != true)) {
                    this.HotelAddressField = value;
                    this.RaisePropertyChanged("HotelAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIDField, value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelName {
            get {
                return this.HotelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelNameField, value) != true)) {
                    this.HotelNameField = value;
                    this.RaisePropertyChanged("HotelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/WcfHotelService")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelListing", Namespace="http://schemas.datacontract.org/2004/07/WcfHotelService")]
    [System.SerializableAttribute()]
    public partial class HotelListing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookedRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelProject.RatingServiceReference.Address HotelAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NearestAirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookedRooms {
            get {
                return this.BookedRoomsField;
            }
            set {
                if ((this.BookedRoomsField.Equals(value) != true)) {
                    this.BookedRoomsField = value;
                    this.RaisePropertyChanged("BookedRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelProject.RatingServiceReference.Address HotelAddress {
            get {
                return this.HotelAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAddressField, value) != true)) {
                    this.HotelAddressField = value;
                    this.RaisePropertyChanged("HotelAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIDField, value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NearestAirport {
            get {
                return this.NearestAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.NearestAirportField, value) != true)) {
                    this.NearestAirportField = value;
                    this.RaisePropertyChanged("NearestAirport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RatingServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRatedHotels", ReplyAction="http://tempuri.org/IService1/GetRatedHotelsResponse")]
        HotelProject.RatingServiceReference.RatedHotel[] GetRatedHotels(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRatedHotels", ReplyAction="http://tempuri.org/IService1/GetRatedHotelsResponse")]
        System.Threading.Tasks.Task<HotelProject.RatingServiceReference.RatedHotel[]> GetRatedHotelsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddHotelRating", ReplyAction="http://tempuri.org/IService1/AddHotelRatingResponse")]
        bool AddHotelRating(string username, string hotelID, float rating, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddHotelRating", ReplyAction="http://tempuri.org/IService1/AddHotelRatingResponse")]
        System.Threading.Tasks.Task<bool> AddHotelRatingAsync(string username, string hotelID, float rating, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BrowseHotels", ReplyAction="http://tempuri.org/IService1/BrowseHotelsResponse")]
        HotelProject.RatingServiceReference.HotelListing[] BrowseHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BrowseHotels", ReplyAction="http://tempuri.org/IService1/BrowseHotelsResponse")]
        System.Threading.Tasks.Task<HotelProject.RatingServiceReference.HotelListing[]> BrowseHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginStaff", ReplyAction="http://tempuri.org/IService1/LoginStaffResponse")]
        bool LoginStaff(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginStaff", ReplyAction="http://tempuri.org/IService1/LoginStaffResponse")]
        System.Threading.Tasks.Task<bool> LoginStaffAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginMember", ReplyAction="http://tempuri.org/IService1/LoginMemberResponse")]
        bool LoginMember(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginMember", ReplyAction="http://tempuri.org/IService1/LoginMemberResponse")]
        System.Threading.Tasks.Task<bool> LoginMemberAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterMember", ReplyAction="http://tempuri.org/IService1/RegisterMemberResponse")]
        bool RegisterMember(string username, string password, float balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterMember", ReplyAction="http://tempuri.org/IService1/RegisterMemberResponse")]
        System.Threading.Tasks.Task<bool> RegisterMemberAsync(string username, string password, float balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllHotels", ReplyAction="http://tempuri.org/IService1/GetAllHotelsResponse")]
        HotelProject.RatingServiceReference.HotelListing[] GetAllHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllHotels", ReplyAction="http://tempuri.org/IService1/GetAllHotelsResponse")]
        System.Threading.Tasks.Task<HotelProject.RatingServiceReference.HotelListing[]> GetAllHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookHotelRooms", ReplyAction="http://tempuri.org/IService1/BookHotelRoomsResponse")]
        bool BookHotelRooms(string hotelID, int roomsToBook, float discountPercent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookHotelRooms", ReplyAction="http://tempuri.org/IService1/BookHotelRoomsResponse")]
        System.Threading.Tasks.Task<bool> BookHotelRoomsAsync(string hotelID, int roomsToBook, float discountPercent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        bool ChangePassword(string username, string newPassword, int userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        System.Threading.Tasks.Task<bool> ChangePasswordAsync(string username, string newPassword, int userType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HotelProject.RatingServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HotelProject.RatingServiceReference.IService1>, HotelProject.RatingServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelProject.RatingServiceReference.RatedHotel[] GetRatedHotels(string username) {
            return base.Channel.GetRatedHotels(username);
        }
        
        public System.Threading.Tasks.Task<HotelProject.RatingServiceReference.RatedHotel[]> GetRatedHotelsAsync(string username) {
            return base.Channel.GetRatedHotelsAsync(username);
        }
        
        public bool AddHotelRating(string username, string hotelID, float rating, string comment) {
            return base.Channel.AddHotelRating(username, hotelID, rating, comment);
        }
        
        public System.Threading.Tasks.Task<bool> AddHotelRatingAsync(string username, string hotelID, float rating, string comment) {
            return base.Channel.AddHotelRatingAsync(username, hotelID, rating, comment);
        }
        
        public HotelProject.RatingServiceReference.HotelListing[] BrowseHotels() {
            return base.Channel.BrowseHotels();
        }
        
        public System.Threading.Tasks.Task<HotelProject.RatingServiceReference.HotelListing[]> BrowseHotelsAsync() {
            return base.Channel.BrowseHotelsAsync();
        }
        
        public bool LoginStaff(string username, string password) {
            return base.Channel.LoginStaff(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginStaffAsync(string username, string password) {
            return base.Channel.LoginStaffAsync(username, password);
        }
        
        public bool LoginMember(string username, string password) {
            return base.Channel.LoginMember(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginMemberAsync(string username, string password) {
            return base.Channel.LoginMemberAsync(username, password);
        }
        
        public bool RegisterMember(string username, string password, float balance) {
            return base.Channel.RegisterMember(username, password, balance);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterMemberAsync(string username, string password, float balance) {
            return base.Channel.RegisterMemberAsync(username, password, balance);
        }
        
        public HotelProject.RatingServiceReference.HotelListing[] GetAllHotels() {
            return base.Channel.GetAllHotels();
        }
        
        public System.Threading.Tasks.Task<HotelProject.RatingServiceReference.HotelListing[]> GetAllHotelsAsync() {
            return base.Channel.GetAllHotelsAsync();
        }
        
        public bool BookHotelRooms(string hotelID, int roomsToBook, float discountPercent) {
            return base.Channel.BookHotelRooms(hotelID, roomsToBook, discountPercent);
        }
        
        public System.Threading.Tasks.Task<bool> BookHotelRoomsAsync(string hotelID, int roomsToBook, float discountPercent) {
            return base.Channel.BookHotelRoomsAsync(hotelID, roomsToBook, discountPercent);
        }
        
        public bool ChangePassword(string username, string newPassword, int userType) {
            return base.Channel.ChangePassword(username, newPassword, userType);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePasswordAsync(string username, string newPassword, int userType) {
            return base.Channel.ChangePasswordAsync(username, newPassword, userType);
        }
    }
}
